### PR TITLE
Iso15693 improvements

### LINKED ISSUE #1771: Standalone hf_tmudford.c compilation error
***Compilation problem***
[-] CC appmain.c
../armsrc/Standalone/hf_tmudford.c: In function 'RunMod':
../armsrc/Standalone/hf_tmudford.c:78:17: error: too few arguments to function 'SimTagIso15693'
   78 |                 SimTagIso15693(card.uid);
      |                 ^~~~~~~~~~~~~~
In file included from ../armsrc/Standalone/hf_tmudford.c:29:
./iso15693.h:51:6: note: declared here
   51 | void SimTagIso15693(uint8_t *uid, uint8_t block_size); // simulate an ISO15693 tag
      |      ^~~~~~~~~~~~~~
make[1]: *** [../common_arm/Makefile.common:119: obj/hf_tmudford.o] Error 1

**Desktop (please complete the following information):**
 - OS: Kali Linux
 - Compiler (ARM):  arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)

### PR DESCRIPTION
**Pull request by markus-oehme-pg40**
I added the write block and write multiple block commands to the `hf 15 sim` emulation and implemented `hf 15 eview` and `hf 15 esave`.

I merged in master to resolve one conflict where both sides did the same thing (fix #1771).

Please consider for inclusion.

### CODE REVIEW

File: client/src/cmdhf15.c [hunk 1]
```diff
@@ -1098,6 +1098,133 @@ static int CmdHF15ELoad(const char *Cmd) {
...
+    PrintAndLogEx(INFO, "Downloading %u bytes from emulator memory", bytes);
+    if (!GetFromDevice(BIG_BUF_EML, dump, bytes, 0, NULL, 0, NULL, 2500, false)) {
+        PrintAndLogEx(WARNING, "Fail, transfer from device time-out");
+        free(dump);
+        return PM3_ETIMEOUT;
+    }
+
+    saveFile(filename, ".bin", dump, bytes);
+    saveFileEML(filename, dump, bytes, blocksize);
+    saveFileJSON(filename, jsf15, dump, bytes, NULL);
```
Comment (iceman1001) [inline client/src/cmdhf15.c:1145]: should be a pm3_save_dump fct ...

File: client/src/cmdhf15.c [hunk 2]
```diff
@@ -1098,6 +1098,133 @@ static int CmdHF15ELoad(const char *Cmd) {
...
+}
+
+static void print_blocks_15693(uint8_t *data, uint16_t bytes, int blocksize) {
+    int blocks = bytes / blocksize;
+    PrintAndLogEx(NORMAL, "");
+    print_hrule(blocksize);
+    PrintAndLogEx(INFO, " blk | data  " NOLF);
+    for (int i = 2; i < blocksize; i++) {
+        PrintAndLogEx(NORMAL, "   " NOLF);
+    }
```
Comment (iceman1001) [inline client/src/cmdhf15.c:1169]: There should be a string formatter option to specify number of chars to be added. 
It will simplify this whole "dynamic create string headers based on block size" a bit

File: CHANGELOG.md [hunk 3]
```diff
@@ -92,6 +92,8 @@ This project uses the changelog in accordance with [keepchangelog](http://keepac
  - Added `script run hf_mf_hid_sim.lua` (@micsen)
  - Added `hf 15 sim --blocksize` - configure block size for simulation (@markus-oehme-pg40)
  - Added `hf 15 eload` - specify memory image for ISO15693 simulation (@markus-oehme-pg40)
+ - Added write command support to `hf 15 sim` (@markus-oehme-pg40)
+ - Added `hf 15 eview` and `hf 15 esave` - Retrieve emulator image for ISO15693 simulation (@markus-oehme-pg40)
```
Comment (iceman1001) [inline CHANGELOG.md:96]: I forgot to mention last time, but we put all entries on the top of the list,  
so move your four entries to the top instead.
We also use,   "Changed",  "Fix",  "Added"  as the first word,   with <cmd> as second::
You write entry becomes:

"Changed `hf 15 sim` - now supports reader writes (@markus-oehme-pg40 )

File: client/src/cmdhf15.c (hunk 2 above)
Comment (markus-oehme-pg40) [reply client/src/cmdhf15.c]: Learned something new about format specifiers there. It indeed looks much better now.

**Comment by iceman1001** [comment]
Great!
Fast changes,  neat code.  I like.
